### ISSUE TITLE
At gamestart, every user of that game gets their money set to starting amount.

### ISSUE THREAD

**Issue by cobankar** [sopra-fs21-group-03/Server#82]
Time estimate: 2h
This task is part of user story #20

**Comment by Samy1101** [comment]
TO DO:
- Finish setup functions in GameEntity (Blinds, Cards, StartMoney, ...)
- Add Method to LoginService to create new GameEntity for Repo
  (This is done since we are skipping the lobby implementation for this milestone)
- Implement Card and Deck
- Implement GameGetDTO and write the GET-Mapping in the gameController

**Comment by mr-carlitos** [comment]
This task still needs to be tested I guess
